### ISSUE TITLE
2015年度用の新卒歓迎会の資料作る

### ISSUE THREAD

**Issue by kfly8** [clubdev2/clubdev2.github.io#3]
http://clubdev2.github.io/

これのブラッシュアップ

* [x] スライド見るだけで、多少意味が通るようにする、、、多少、、、
* [x] ロゴをいい感じに配置したい 
  * 今は、縦横比を無視して、引き伸ばしておいてしまって申し訳ない感じ、、
  * http://clubdev2.github.io/?full#Cover
* [x] ~~成果物をもう少し列挙したい~~
  * https://github.com/clubdev2/clubdev2.github.io/blob/master/index.html#L138
* [x] メンバー構成比に新しく追加された Unity と 井澤詩織 にも言及したい
  * https://github.com/clubdev2/clubdev2.github.io/blob/master/index.html#L22-L23
* [ ] 花澤香菜の画像を新しくしたい

**Comment by kfly8** [comment]
残り余力があったら、やる？
だれがやっても、おっけー（というより誰かやってほしい）

**Comment by masasuzu** [comment]
しーたむの画像はさがしておく

**Comment by masasuzu** [comment]
雑に井澤さんの画像とUnityの画像を追記して、グラフの文字が見えるように調整しておきました。
気になる人がちょっと修正してください。

**Comment by masasuzu** [comment]
そしてコミットログのissue id間違えた

**Comment by masasuzu** [comment]
本当にこのパーセンテージで良いですか? 誰も異論上がってないですが。

https://github.com/clubdev2/clubdev2.github.io/blob/master/index.html#L13-L25

**Comment by kfly8** [comment]
もっと好きな声優、キャラいるんじゃないかと思うところはありますが、、
いいんじゃないかと思ってますw

免責事項もいれてある？
https://github.com/clubdev2/clubdev2.github.io/blob/master/index.html#L167

**Comment by masasuzu** [comment]
@rymizuki なんじょーさん入れなくて良いの?

**Comment by kfly8** [comment]
時効

**Comment by karupanerura** [comment]
2016年版を作らないと！
